spring.application.name=api-gateway


server.port=8060

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


spring.cloud.gateway.routes[0].id=inventory-service
spring.cloud.gateway.routes[0].uri=http://localhost:7002
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/inventorys/**
spring.cloud.gateway.routes[1].id=order-product-service
spring.cloud.gateway.routes[1].uri=http://localhost:8003
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orderproduct/**
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=http://localhost:8002
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[3].id=product-service
spring.cloud.gateway.routes[3].uri=http://localhost:8001
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/products/**
spring.cloud.gateway.routes[4].id=stores-service
spring.cloud.gateway.routes[4].uri=http://localhost:7001
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/stores/**
spring.cloud.gateway.routes[5].id=users-service
spring.cloud.gateway.routes[5].uri=http://localhost:9099
spring.cloud.gateway.routes[5].predicates[0]=Path=/person/**



#spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter
#spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# Enable CORS if needed
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*

# Enable actuator endpoints for monitoring
management.endpoints.web.exposure.include=*
